# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_auto_20170728_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comments_text',
            field=models.TextField(),
        ),
    ]
