# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_article_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comments_autor',
            field=models.CharField(default='\u0410\u043d\u043e\u043d\u0438\u043c', max_length=120),
        ),
    ]
