# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 11:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_comments_comments_autor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='comments_autor',
            new_name='comments_author',
        ),
    ]
