# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0007_auto_20170810_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comments_author',
            field=models.CharField(max_length=120),
        ),
    ]
